cas:
    jdbc:
        show-sql: true
    authn:
        accept:
            enabled: false
        throttle:
            failure:
                #在上述时间段内允许的失败登录尝试次数
                threshold: 1
                #时间范围
                rangeSeconds: 3
                throttleWindowSeconds: "PT600S"
        oauth:
            crypto:
                signing:
                    key: M8z5otNBibl_t5N5fFBXOdHmQTH8_zNDFmsxzCdUZB-iyBESvMidYhTJi5d9SQP5QKrFB0YxfFy9-Vz_5bqeGQ
                encryption:
                    key: NpqJTkfnGXMzBYycIfKO1x0m05YwE7s_nZzJ1_TQAQ-Cu88gzQiL9lZ-1vse6DZtXzWGSsny1PX73XLOY953Cw
            refreshToken:
                timeToKillInSeconds: P14D
            code:
                timeToKillInSeconds: 600
                numberOfUses: 1
            access-token:
                timeToKillInSeconds: PT2H
                maxTimeToLiveInSeconds: PT8H
                createAsJwt: true
                crypto:
                    encryption:
                        key: QTGrm8G1uf6rwx0arh-_DkeqorpkL-mLZQuqB8R6gGqtXqHMKZ0Kti1uegxBE0A9k3OeH3nNXy6pN4pik9G2HQ
                    signing:
                        key: 4i8FZ6p_Zf6QT9wk0AVpPyDjafVvQkVc05TwWa_gJrF5FxQh5nEOu5alDnstbEE1DqcCDRYAABhkQ2t_S8CrdA
            grants:
                resourceOwner:
                    requireServiceHeader: true
            core:
                userProfileViewType: FLAT
                bypassApprovalPrompt: true
            session-replication:
                cookie:
                    crypto:
                        encryption:
                            key: SorpInDU8UOA-ml02lgVAwzxT63DTnfFBV6656W-ANasCqg8dJPWuDQIHpIaK6UCgXcUnx1i86kqF53BVxqu_g
                        signing:
                            key: mwNIgj-1CQf8pvMoAfEhtdg-AS-KIMcYGA5eMeU5kKNip-b3iIP_Ch4ghn5ndVQUH-KZFh_YBoFEg8zmq3Ec6A
                    secure: false
                    path: /sso/
                    sameSitePolicy: Lax
        oidc:
            core:
                issuer: http://localhost:7055/sso/oidc
                user-defined-scopes:
                    y9: "tenantId,tenantShortName,tenantName,personId,loginName,sex,caid,email,mobile,guidPath,dn,loginType,name,parentId,idNum,avator,personType,password,original,originalId,globalManager,managerLevel,positions,positionId,deptId"
            discovery:
                scopes: "openid,y9"
                claims: "sub,gender,tenantId,tenantShortName,tenantName,personId,loginName,sex,caid,email,mobile,guidPath,dn,loginType,name,parentId,idNum,avator,personType,password,original,originalId,globalManager,managerLevel,positions,positionId,deptId"
            jwks:
                fileSystem:
                    jwksFile: classpath:/keystore.jwks
        token:
            crypto:
                signing:
                    key: "28T9g6Acy12Qy3x89U43btgkyRumyzMQzK6Cxl6KiVYtnfgHIaBzNP7IG6nArCzn06K_0TccfFTLan-ZPyDRcA"
                encryption:
                    key: "qs8_64oANNxLXHy4YAHZTahXBN8-7AKVUtVxuevpo7R7IYJ0a-nOJqpmnOgjrlBjyGgccz-VEm6LYjncyq5pEg"
    server:
        name: http://localhost:7055
        prefix: http://localhost:7055/sso
    service-registry:
        cache:
            duration: PT8H
            cacheSize: 10000
            initialCapacity: 1000
        core:
            # 建议仅用于测试（集群部署时需考虑service.json的同步，使用jpa-service-registry即可）
            initFromJson: true
        json:
            location: classpath:/services
            watcherEnabled: true
        jpa:
            enabled: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
            driver-class: org.postgresql.Driver
            url: jdbc:postgresql://localhost:5432/postgres
            user: root
            password: '11111111'
            idleTimeout: PT10M
            leakThreshold: 0
            autocommit: true
            ddl-auto: update
            pool:
                min-size: 6
                max-size: 18
                maximum-lifetime: PT15M
        schedule:
            enabled: true
            repeatInterval: "PT30M"
            startDelay: "PT2M"

    ticket:
        trackDescendantTickets: true
        registry:
            core:
                enable-locking: true
            cleaner:
                schedule:
                    enabled: true
                    startDelay: PT15S
                    repeatInterval: PT30M
            jpa:
                enabled: false
                dialect: org.hibernate.dialect.PostgreSQLDialect
                driver-class: org.postgresql.Driver
                url: jdbc:postgresql://localhost:5432/postgres
                user: root
                password: "11111111"
                leakThreshold: 0
                idleTimeout: PT5M
                autocommit: true
                ddl-auto: update
                crypto:
                    enabled: true
                    encryption:
                        key: "6vJAg4gWORY0f8dF5XIc8Q"
                    signing:
                        key: "CzPeT3D2l7C-dwR2LfV9DFHrwmPGXCSsEReZeTn76xiWNU45De8s1CAdPNXovoBpEilbeTY1PkwPQuMxZdN4mQ"
            redis:
                enabled: true
                useSsl: false
                host: "localhost"
                port: 6379
                database: 0
                username: default
                password: "11111111"
                timeout: "PT60S"
                pool:
                    enabled: true
                    testWhileIdle: true
                    maxActive: 20
                    maxIdle: 5
                    maxWait: 1000
                    minIdle: 1
                crypto:
                    enabled: true
                    encryption:
                        key: "6vJAg4gWORY0f8dF5XIc8Q"
                        keySize: 16
                    signing:
                        key: "CzPeT3D2l7C-dwR2LfV9DFHrwmPGXCSsEReZeTn76xiWNU45De8s1CAdPNXovoBpEilbeTY1PkwPQuMxZdN4mQ"
                        keySize: 512
                cache:
                    initial-capacity: 0
        st:
            maxLength: 50
            numberOfUses: 10
            timeToKillInSeconds: 600
        tgt:
            primary:
                maxTimeToLiveInSeconds: 28800
                timeToKillInSeconds: 7200
            core:
                maxLength: 50
            rememberMe:
                enabled: false
                timeToKillInSeconds: 28800
                #supportedUserAgents:
                #supportedIpAddresses: 127.0.0.1,0:0:0:0:0:0:0:1
    tgc:
        httpOnly: true
        maxAge: -1
        name: TGC
        path: /sso/
        pinToSession: true
        rememberMeMaxAge: P14D
        secure: false
        sameSitePolicy: Lax
        crypto:
            encryption:
                key: P0sPPaRh2CYrJbEAH-HJYZmmQJfazFUyKSzHDKKaEtitNtjeATeGgJ6rqKdhKDoSXbDOPdxS4J7A89s-xOm1fw
            signing:
                key: 9SlzKqi2XsI-JbI81_4ayaq9uemKLa5z4HmPDO-IjPxsWozsqZeO7wujRLNJenDp23CiZLw79qwg1xhRccZdrg
    webflow:
        crypto:
            signing:
                key: gALDjXB_HKK7u7ZduHAPBx3BQs0Rr36AVXnDm9HMG--WDJow5qdLJZsXwTsEmGcrwXTwEXm5u85z07C29ekrKw
            encryption:
                key: xbucxsc352uVfreOOmBttQ
    httpClient:
        allowLocalUrls: true
        hostNameVerifier: none
    httpWebRequest:
        header:
            xframe: false
            xframeOptions: SAMEORIGIN
            #contentSecurityPolicy: 'frame-ancestors http://localhost:* http://127.0.0.1:* http://192.168.56.1:*'
        cors:
            enabled: true
            allowCredentials: true
            allowHeaders: "*"
            allowMethods: "*"
            allowOriginPatterns: "*"
            maxAge: 36000
    locale:
        defaultValue: zh_CN
    theme:
        defaultThemeName: y9-apereo
        #defaultThemeName: cas-theme-default
        paramName: theme
    messageBundle:
        useCodeMessage: true
        fallbackSystemLocale: true
    view:
        #当service参数为空时，利用defaultRedirectUrl
        #defaultRedirectUrl: http://localhost:7099
        #当defaultRedirectUrl为空、并且service参数为空时，自动计算service
        authorizedServicesOnSuccessfulLogin: true
        custom-login-form-fields:
            loginType:
                required: true
                messageBundleKey: customLoginFormField.loginType
            tenantShortName:
                required: true
                messageBundleKey: customLoginFormField.tenantShortName
            screenDimension:
                required: false
                messageBundleKey: customLoginFormField.screenDimension
            systemName:
                required: false
                messageBundleKey: customLoginFormField.systemName
            deptId:
                required: false
                messageBundleKey: customLoginFormField.deptId
            positionId:
                required: false
                messageBundleKey: customLoginFormField.positionId
    logout:
        confirm-logout: false
        follow-service-redirects: true
        # redirect-parameter: "service"
        # redirect-url: http://localhost:7055/sso/login
    slo:
        asynchronous: false
        disabled: false
        logoutPropagationType: AJAX
    monitor:
        endpoints:
            endpoint:
                defaults:
                    access: ANONYMOUS
logging:
    level:
        org:
            apereo:
                cas:
                    ticket:
                        registry: debug
                inspektr: warn
        root: warn
server:
    port: 7055
    servlet:
        context-parameters:
            isLog4jAutoInitializationDisabled: true
        context-path: /sso
        session:
            cookie:
                http-only: true
                secure: false
            timeout: 300
            tracking-modes: COOKIE
    shutdown: graceful
    ssl:
        enabled: false
    tomcat:
        accesslog:
            enabled: true
            pattern: '%t %a "%r" %s (%D ms)'
            suffix: .log
        additional-tld-skip-patterns: '*.jar'
        background-processor-delay: 0s
        basedir: build/tomcat
        connection-timeout: PT20S
        max-http-form-post-size: 2097152
        remoteip:
            port-header: X-Forwarded-Port
            protocol-header: X-Forwarded-Proto
            protocol-header-https-value: https
            remote-ip-header: X-FORWARDED-FOR
        threads:
            max: 400
            min-spare: 10
        uri-encoding: UTF-8
management:
    auditevents:
        enabled: true
    endpoint:
        restart:
            access: NONE
        shutdown:
            access: NONE
    endpoints:
        access:
            default: unrestricted
        jmx:
            exposure:
                exclude: '*'
        web:
            base-path: /actuator
            discovery:
                enabled: true
            exposure:
                include: info,health,status
    server:
        add-application-context-header: false
    tracing:
        export:
            enabled: true
spring:
    application:
        name: sso
    autoconfigure:
        exclude:
            # 需要使用 kafka 时注释掉让其能自动配置
            - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
            - org.springframework.boot.actuate.autoconfigure.metrics.KafkaMetricsAutoConfiguration
    cloud:
        nacos:
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: local
                server-addr: http://localhost:8848
                username: nacos
                password: ${NACOS_PASSWORD:11111111}
            discovery:
                enabled: false
        compatibility-verifier:
            enabled: false
    config:
        import:
            - optional:nacos:sso.yml
    datasource:
        hikari:
            driverClassName: org.postgresql.Driver
            jdbcUrl: jdbc:postgresql://localhost:5432/postgres
            username: root
            password: '11111111'
            maximumPoolSize: 20
            minimumIdle: 1
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                hbm2ddl:
                    auto: update
                jdbc:
                    batchSize: 100
                showSql: true
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
    docker:
        compose:
            enabled: false
            file: docker-dev.yml
    integration:
        jdbc:
            initialize-schema: always
    jmx:
        enabled: false
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            retries: 0
            batch-size: 20960
            buffer-memory: 67108864
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9sso-server
    session:
        timeout: 3600
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: false
        lazy-initialization: false
    security:
        user:
            name: y9admin
            password: risesoft
y9:
    #kafka , jpa
    loginInfoSaveTarget: jpa
    internalIp: 192.168.x.x,10.0.x.x,172.20.x.x
    rsaPublicKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC6DvO5m7p1Of/IkPwMRdQK7tx4wZKrbmVj2aqhlX5z+McbxeiP1XgwpiFINxigtXqU49rtCb1eyUafD4lIYZ399Z5TAZeD3kH+ggdP6xRr0G7+u1UE9qgoLXPOugZsABwSOq5w9v6qGUAY8U3doLDkjCueMbEeGG96FjqaaMLckwIDAQAB"
    rsaPrivateKey: "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALoO87mbunU5/8iQ/AxF1Aru3HjBkqtuZWPZqqGVfnP4xxvF6I/VeDCmIUg3GKC1epTj2u0JvV7JRp8PiUhhnf31nlMBl4PeQf6CB0/rFGvQbv67VQT2qCgtc866BmwAHBI6rnD2/qoZQBjxTd2gsOSMK54xsR4Yb3oWOppowtyTAgMBAAECgYACb5OtSGamhj3dCFjkaD2gbwQf6Jjc+bMGHaFoQCbJqeYhbPPgfjD2ohYpdd8yq22RaXJCTDBYf1YXWwK3GeARn19tYnJodqspAya3jyfSFY+IRDQ2kQ/59w1VmBiOtJsUJG4va2Bz9SRfLZuXwOyznjKk7BE89Anb3ici6u6HYQJBAONiagv+Kc8dkxoip1NWYVFjCWNHTejWTgLLgVDZi1jep/8Xx5d5E1aewcvPCJRz8A7hYEY5Uc8Mt9PB6NhLedkCQQDReSXdMdg+/lLYwdX7lRfPH7PIGNK4UwmZQ0LW7fsoy8/TD9gMnQ9sAVHILKxQuhubDHGfonVhA08WA2nvgzpLAkEA0hMmbpYPAm8MbOT/OhtgJdUd4z8JV8hGooZpnsyd1SlAhIjvuZ3+o9Rgr29DOgQzEUxfqgFi96uEWnuYJ9zzYQJBAK0SL5qmiEjj0IeO/8Gx2c4kH2KAP/pTgWbEEAGM9ysp2jhEqvkg+5D9Nhjx8B1y50Qf7/E5RUo2da12fJyMDCkCQDjBuq+dssaPGs36oijHBxzJmeaFR6vmKBUaiwYJEHg2ayi3r3/dHRrqYxXC2wblxOhkytUl/R1DErHztHHm878="