name: y9-dev-postgres-keycloak
services:
  nginx:
    image: nginx:1.29.3-trixie
    container_name: nginx01
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - y9-share-net
    volumes:
      - d:/docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- d:/docker-config/nginx/conf.d:/etc/nginx/conf.d
      - d:/docker-config/nginx/cert:/etc/nginx/cert
      #- d:/docker-config/nginx/html:/usr/share/nginx/html
      #- d:/docker-data/nginx/logs:/var/log/nginx
    
networks:
  y9-share-net:
    external: true
    
# docker compose -f compose-nginx.yml up -d
